# default uses hash.yaml
hash_path = "hash.yaml"

# MD5, SHA1, SHA256
hash_meth = "MD5"

# should almost always be .
git_path = "."

# regex patterns to match
regex_matches = ['.+']

# username to use for addcommit option
username = "anonymous"

# email address to use for addcommit option
email = "anonymous@xxx.com"